name: fly deploy

on:
  push:
    branches: [main]
    paths-ignore:
      - '**.md'
      - 'tmp/**'
  workflow_dispatch:

concurrency:
  group: fly-deploy-prod
  cancel-in-progress: false

jobs:
  deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
      - uses: actions/checkout@v4
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - run: flyctl deploy --remote-only --strategy rolling
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
